
[PowerStation.PW2]
PwrSttAdd = "PW 2"
vendor_id = 0x098F
product_id = 0x1001
v_dvdd = 1.8
v_avdd = 1.8
v_pwell = 6.0
v_sub = 6.0
i_dvdd = 0.7
i_avdd = 0.7
i_pwell = 0.05
i_sub = 0.05
short_circuit_threshold_pct = 0.5


[PowerStation.PW1]
PwrSttAdd = "PW 1"
vendor_id = 0x098F
product_id = 0x1001
v_dvdd = 1.8
v_avdd = 1.8
v_pwell = 6.0
v_sub = 6.0
i_dvdd = 0.7
i_avdd = 0.7
i_pwell = 0.05
i_sub = 0.05
short_circuit_threshold_pct = 0.5

[MaltaDAQ.W4R1_W2R6]
binary_path = "/home/MaltaSW/build/MaltaDAQ/MaltaMultiDAQ"
daq_config =  "/home/MaltaSW/MaltaDAQ/configs/2DUT_Const_Test.txt"
work_dir = "/home/MaltaSW/MaltaDAQ"
monitor_dir = "/home/MaltaSW/ReadyJuneBeamtest/config/2malta_dut"
monitor_script = "run_onlinemonitor.sh"
_conditions.require_stopping_after = ["MaltaTLU.TLU"]

[MaltaTLU.TLU]
bridge_python = "/home/atlas/sw/lcg/releases/LCG_104d/Python/3.9.12/x86_64-el9-gcc13-opt/bin/python3"
bridge_script = "/home/itdc/work/Thomas/Constellation/Bridge.py"
uri = "192.168.200.20"
address_table = "/home/MaltaSW/MaltaTLU_AlinxSW/configs/tlu_addresses.xml"
bridge_repo_root = "/home/MaltaSW/MaltaTLU_AlinxSW/"
bridge_pythonpath = "/home/MaltaSW/installed/x86_64-el9-gcc13-opt/lib:/home/MaltaSW/installed/share/lib/python"
bridge_ld_library_path = "/home/atlas/sw/lcg/releases/gcc/13.1.0-b3d18/x86_64-el9/lib64:/home/atlas/sw/lcg/releases/gcc/13.1.0-b3d18/x86_64-el9/lib:/home/MaltaSW/installed/x86_64-el9-gcc13-opt/lib"
sc_enabled = false
plane_1 = true
plane_2 = true
plane_3 = false
plane_4 = false
plane_5 = false
plane_6 = false

veto_SC = 1
veto_1 = 1
veto_2 = 1
veto_3 = 1
veto_4 = 1
veto_5 = 1
veto_6 = 1

max_rate_hz = 0
max_rate_enabled = true
L1A = 1000

width_SC = 80
width_1 = 80
width_2 = 80	
width_3 = 80
width_4 = 80
width_5 = 80
width_6 = 80
width_L1A = 100

_conditions.require_starting_after = ["MaltaDAQ.W4R1_W2R6"]


